### ISSUE TITLE
Target(t)ing broke!

### ISSUE THREAD

**Issue by JohannesBertens** [weisluke/WoTMUD#1]
Files currently available for installation:
   File type: timers
       status_bar
   File type: scripts
       alt_timer
       communications
       mapper
       player_numbers
       status_bar
       tic_timer
       vote_wotmud
   File type: keys
       numpad
       mapper
   File type: triggers
       character_status_color
       communications
       delete_lines
       gating
       hp-mv-sp_colors
       locates
       mapper
       melee_colors
       miscellaneous
       player_numbers
       room_highlights
       status_bar
       tic_timer
       weave_colors
   File type: aliases
       communications
       containers
       doors
       gating
       horses
       lights
       mapper
       master_mob
       pk
       player_numbers
       targeting
       tic_timer
       vials
       vote_wotmud
       weapons

wotpack install targeting
<< nothing!! >>

wotpack install all
(wotpack_installer): Old status_bar_timers uninstalled.
(wotpack_installer): New status_bar_timers successfully installed.
(wotpack_installer): Old player_numbers_scripts uninstalled.
(wotpack_installer): New player_numbers_scripts successfully installed.
(wotpack_installer): Old status_bar_scripts uninstalled.
(wotpack_installer): Old mapper_scripts uninstalled.
(wotpack_installer): Old numpad_keys uninstalled.
(wotpack_installer): Old vote_wotmud_scripts uninstalled.
(wotpack_installer): Old character_status_color_triggers uninstalled.
(wotpack_installer): Old mapper_keys uninstalled.
(wotpack_installer): Old communications_triggers uninstalled.
(wotpack_installer): Old delete_lines_triggers uninstalled.
(wotpack_installer): New delete_lines_triggers successfully installed.
(wotpack_installer): New communications_triggers successfully installed.
(wotpack_installer): New mapper_keys successfully installed.
(wotpack_installer): New character_status_color_triggers successfully installed.
(wotpack_installer): New vote_wotmud_scripts successfully installed.
(wotpack_installer): New numpad_keys successfully installed.
(wotpack_installer): Old tic_timer_scripts uninstalled.
(wotpack_installer): Old gating_triggers uninstalled.
(wotpack_installer): Old locates_triggers uninstalled.
(wotpack_installer): Old hp-mv-sp_colors_triggers uninstalled.
(wotpack_installer): New hp-mv-sp_colors_triggers successfully installed.
(wotpack_installer): Old mapper_triggers uninstalled.
(wotpack_installer): New mapper_triggers successfully installed.
(wotpack_installer): New locates_triggers successfully installed.
(wotpack_installer): New gating_triggers successfully installed.
(wotpack_installer): New tic_timer_scripts successfully installed.
    WoTMUD Mapping Script

    This script will both follow movements through currently known rooms and allow for the
    creation of new rooms. It requires "color complete" to be turned on in the MUD for room
    names to be properly captured, and "autoexits" to be turned on to be able to determine
    room exits. Both are necessary for the script to function properly. The script will work
    with or without "brief" mode turned on in the MUD, though it will be more accurate with
    brief mode off. You can choose to have the script hide room descriptions instead.
    
    KNOWN BUGS: Circle of Dark room name sometimes gets deleted when script is told to hide
        room descriptions. Cause unknown, as I haven't been able to duplicate this error in
        any other rooms.
    
    Below is a brief overview of commonly used commands that this script includes.
    Additional information for further areas is available as well, though every command may
    not be described here. All commands can be found in the appropriate mapper folder under
    mudlet aliases.

    Common Commands:
        map help (optional subfolder name) - Shows either this help file or the help file for
            the subfolder given (e.g. map help booleans, map help doors, etc.)
        map show - Displays or hides a map window in a fixed position. Toggle off and restart
            mudlet in order to make the map a dockable window via the mudlet toolbar map button
        map debug - Toggles debug mode, in which extra messages are shown with the intent of
            assisting in troubleshooting. Default: on
        resetqueue - Clears the list of movement commands maintained by the script. Useful
            if map appears to not be following correctly, or if aliases to open doors appear
            to not work properly
        map update - Downloads, saves, and loads the latest version of the WoTMUD_map.dat file
            from https://github.com/weisluke/WoTMUD
        map brief - Toggle whether map script should hide or show the descriptions from
            rooms. Default: show
            
    Information subfolders: These are sub-folders containing information for more commands
        booleans - Map variables that can be toggled on/off
        creation - Commands used in creating new areas and rooms
        doors - Commands used in creating and editing doors
        room data - Commands used in viewing and changing room data
        room colors - Commands used in viewing and changing room colors
        key variables - Variables used by the script to keep track of important information
        map window - Altering the size and position of the map display
        misc - Miscellaneous commands
        
(wotmudmapper): Loading map configurations.
(wotmudmapper): Map configurations loaded.
(wotpack_installer): New mapper_scripts successfully installed.
(wotpack_installer): New status_bar_scripts successfully installed.
(wotpack_installer): Old alt_timer_scripts uninstalled.
(wotpack_installer): Old melee_colors_triggers uninstalled.
(wotpack_installer): Old miscellaneous_triggers uninstalled.
(wotpack_installer): Old status_bar_triggers uninstalled.
(wotpack_installer): Old weave_colors_triggers uninstalled.
(wotpack_installer): New weave_colors_triggers successfully installed.
(wotpack_installer): New status_bar_triggers successfully installed.
(wotpack_installer): Old tic_timer_triggers uninstalled.
(wotpack_installer): Old containers_aliases uninstalled.
(wotpack_installer): Old doors_aliases uninstalled.
(wotpack_installer): Old gating_aliases uninstalled.
(wotpack_installer): Old lights_aliases uninstalled.
(wotpack_installer): New lights_aliases successfully installed.
(wotpack_installer): Old horses_aliases uninstalled.
(wotpack_installer): Old master_mob_aliases uninstalled.
(wotpack_installer): Old pk_aliases uninstalled.
(wotpack_installer): Old vials_aliases uninstalled.
(wotpack_installer): Old vote_wotmud_aliases uninstalled.
(wotpack_installer): Old weapons_aliases uninstalled.
(wotpack_installer): New weapons_aliases successfully installed.
(wotpack_installer): New vote_wotmud_aliases successfully installed.
(wotpack_installer): New vials_aliases successfully installed.
(wotpack_installer): Old tic_timer_aliases uninstalled.
(wotpack_installer): New tic_timer_aliases successfully installed.
(wotpack_installer): Old player_numbers_aliases uninstalled.
(wotpack_installer): New player_numbers_aliases successfully installed.
(wotpack_installer): Old mapper_aliases uninstalled.
(wotpack_installer): New mapper_aliases successfully installed.
(wotpack_installer): New pk_aliases successfully installed.
(wotpack_installer): New master_mob_aliases successfully installed.
(wotpack_installer): New horses_aliases successfully installed.
(wotpack_installer): New gating_aliases successfully installed.
(wotpack_installer): New doors_aliases successfully installed.
(wotpack_installer): Old communications_aliases uninstalled.
(wotpack_installer): New communications_aliases successfully installed.
(wotpack_installer): New containers_aliases successfully installed.
(wotpack_installer): New tic_timer_triggers successfully installed.
(wotpack_installer): Old player_numbers_triggers uninstalled.
(wotpack_installer): New player_numbers_triggers successfully installed.
(wotpack_installer): Old room_highlights_triggers uninstalled.
(wotpack_installer): New room_highlights_triggers successfully installed.
(wotpack_installer): New miscellaneous_triggers successfully installed.
(wotpack_installer): New melee_colors_triggers successfully installed.
(wotpack_installer): New alt_timer_scripts successfully installed.
(wotpack_installer): Old communications_scripts uninstalled.
(wotpack_installer): New communications_scripts successfully installed.

...
NO TARGET(T)ING!

**Comment by weisluke** [comment]
Fixed. List of available files in the wotpack_installer.mpackage had "targeting" but the file on Github was still named "targetting". Renamed the Github file to correct the issue.
