### ISSUE TITLE
Can't see how to get a completely free-floating map display

### ISSUE THREAD

**Issue by SlySven** [weisluke/WoTMUD#34]
I am fortunate enough to have a triple-head PC as my main system so I like to have a MUD's map as the fully floating / dockable widget which I can move to a second screen and have it full-screen there. I would do this in the past by using the "Map" main toolbar button to generate the mapper and NOT use either **[`createMapper(...)`](https://wiki.mudlet.org/w/Manual:Mapper_Functions#createMapper)** or the Geyser equivalent **[`Geyser.Mapper:new(...)`](https://wiki.mudlet.org/w/Manual:Geyser#Create_Map_Window)** but instead click on the map button.

It is now possible to achieve the latter result by using **[`openMapWidget(...)`](https://wiki.mudlet.org/w/Manual:Mapper_Functions#openMapWidget)** (and its associated functions) instead - but it is not possible to switch between the two types (EITHER: confined to within {either docked to one edge or free floating} the main console OR: a full float-able to anywhere on the Desktop or dockable to one edge of the **Mudlet** application window {not the **Profile's one**!}) without restarting the profile...

Currently though - there does not appear to be any support for this alternative in the current WoTMUD package collection - I have started to play around with the system but i was wondering whether anyone already had anything up their sleeves...

**Comment by weisluke** [comment]
I just added another alias to (hopefully) resolve this issue. You can now type "map widget" to have my map scripts toggle between using the openMapWidget() function, or the Adjustable.Container I currently use. As you already know, you'll have to restart after toggling this option on, but hopefully this resolves the issue!

Let me know any further thoughts or suggestions :)
